version: '2.1'

services:
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "blog"
      TZ: "Asia/Shanghai"
    ports:
      - "3306:3306"
  